[workspace]
members = [
    "sandcat-sdk",
    "api",
    "components",
    "i18n",
    "icons",
    "pages",
    "utils",
    "web_rtc",
    "ws",
    "src-tauri",
]
resolver = "2"
default-members = ["pages"]
