[serve]
address = "0.0.0.0"
port = 8080
ws_protocol = "ws"
[[proxy]]
rewrite = "/api/"
backend = "http://127.0.0.1:50001/"
no-system-proxy = true
#backend = "http://192.168.28.120:3000/"
[watch]
# Paths to ignore.
ignore = [ ".git", "dist", ".gitignore", "src-tauri"]
